# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2022-04-21 10:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locaddress', models.CharField(max_length=400)),
                ('locationusage', models.CharField(choices=[('prop', 'Property location'), ('near', 'Nearest Location')], max_length=4)),
                ('locationname', models.CharField(max_length=400)),
                ('lati', models.FloatField(max_length=200)),
                ('longi', models.FloatField(max_length=200)),
                ('otherdetails', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='PropertyDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=400)),
                ('ploatarea', models.CharField(max_length=200)),
                ('bedrooms', models.IntegerField()),
                ('bathrooms', models.IntegerField()),
                ('balconies', models.IntegerField()),
                ('totalrooms', models.IntegerField()),
                ('totalfloors', models.IntegerField()),
                ('houseimage', models.FileField(upload_to='')),
                ('houseimage2', models.FileField(upload_to='')),
                ('houseimage3', models.FileField(upload_to='')),
                ('neighbour', models.CharField(max_length=400)),
                ('aboutprop', models.CharField(max_length=400)),
                ('cost', models.CharField(default='0', max_length=400)),
                ('agents', models.IntegerField(default=0)),
                ('status', models.CharField(default='unsold', max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='locationdetails',
            name='propid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seller.PropertyDetails'),
        ),
        migrations.AddField(
            model_name='locationdetails',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
