# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2022-04-21 10:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyRequests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='unsold', max_length=400)),
                ('price', models.CharField(max_length=400)),
                ('message', models.CharField(max_length=400)),
            ],
        ),
    ]
