# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2022-04-21 10:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('buyer', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('seller', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyrequests',
            name='requestedProperty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seller.PropertyDetails'),
        ),
        migrations.AddField(
            model_name='propertyrequests',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
